TrainingArguments:
  num_train_epochs: 1
  warmup_steps: 200
  per_device_train_batch_size: 1
  weight_decay: 0.01
  logging_steps: 50
  eval_strategy: steps
  eval_steps: 250
  save_steps: 250
  gradient_accumulation_steps: 16
  learning_rate: 5e-5
  lr_scheduler_type: "linear"