TrainingArguments:
  num_train_epochs: 3
  warmup_steps: 500
  per_device_train_batch_size: 1
  weight_decay: 0.01
  logging_steps: 1000
  eval_strategy: steps
  eval_steps: 1000
  save_steps: 1000
  gradient_accumulation_steps: 16
  learning_rate: 3e-5
