#yaml used for configuration management,pipeline setting
#configuration = instr. or settings that tells the program how it should run

artifacts_root: artifacts 
# it will create a artifacts folder and will save all the generation or components within it

data_ingestion:
   root_dir: artifacts/data_ingestion
   source_URL:  https://github.com/S-K-Prusti/Text-Summarizer-Project/raw/main/samsum_data.zip
   local_data_files: artifacts/data_ingestion/data.zip
   unzip_dir: artifacts/data_ingestion

data_validation:
   root_dir: artifacts/data_validation
   STATUS_FILE: artifacts/data_validation/status.txt
   ALL_REQUIRED_FILES: ["train","test","validation"]

data_transformation:
   root_dir: artifacts/data_transformation
   data_path: artifacts/data_ingestion/samsum_dataset
   tokenizer_name: sshleifer/distilbart-cnn-12-6


model_trainer:
   root_dir: artifacts/model_trainer
   data_path: artifacts/data_transformation/samsum_dataset
   model_ckpt: sshleifer/distilbart-cnn-12-6

model_evaluation:
   root_dir: artifacts/model_evaluation
   data_path: artifacts/data_transformation/samsum_dataset
   model_path: artifacts/model_trainer/bart-samsum-model
   tokenizer_path: artifacts/model_trainer/tokenizer
   metric_file_name: artifacts/model_evaluation/metrics.csv
